export const STEPS = {
  WELCOME: 'WELCOME',
  PROFESSIONAL: 'PROFESSIONAL',
  SERVICE: 'SERVICE',
  DATE: 'DATE',
  TIME: 'TIME',
  NOTES: 'NOTES',
  IDENTIFY: 'IDENTIFY',
  EXISTING_CLIENT: 'EXISTING_CLIENT',
  NEW_CLIENT: 'NEW_CLIENT',
  SUMMARY: 'SUMMARY',
}

export const STEP_ORDER = [
  STEPS.WELCOME,
  STEPS.PROFESSIONAL,
  STEPS.SERVICE,
  STEPS.DATE,
  STEPS.TIME,
  STEPS.NOTES,
  STEPS.IDENTIFY,
  STEPS.SUMMARY,
]

// Passos que contam para a barra de progresso (identificação é tratada à parte)
export const PROGRESS_STEPS = [
  STEPS.PROFESSIONAL,
  STEPS.SERVICE,
  STEPS.DATE,
  STEPS.TIME,
  STEPS.NOTES,
  STEPS.IDENTIFY,
  STEPS.SUMMARY,
]
